"""One shell for every page of hazardpulse.com.

Every page -- generated by a scorer or kept by hand -- is ``document(path, main_html)``: the same
<head> (title, description, canonical URL, social cards, versioned assets), the same header and the
same footer. Generators call ``document`` directly; hand-kept pages are re-wrapped by
``rewrap_static_pages`` on every build, so a change here reaches every page and no page can drift
(tests/test_site_shell.py fails if one does).

Rules the shell enforces for the whole site (the Content-Security-Policy allows nothing else):
no inline ``style`` attributes, no inline executable scripts, assets served from /assets only.
"""
from __future__ import annotations

import hashlib
import html
import json
import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DIST = ROOT / "dist"
DOMAIN = "https://hazardpulse.com"
CONTACT_EMAIL = "josh@coherenceenergylabs.com"
DATA_RELEASE_URL = "https://github.com/coherence-energy-labs/hazardpulse/releases"
SOURCE_URL = "https://github.com/coherence-energy-labs/hazardpulse"
OG_IMAGE = "/assets/og-card.png"
YEAR = 2026


@dataclass(frozen=True)
class Page:
    path: str
    title: str                 # the <title>, without the brand suffix
    description: str           # meta description, <= 160 characters
    static: bool = False       # kept by hand in dist/ and re-wrapped on every build
    noindex: bool = False
    jsonld: dict | None = field(default=None, hash=False, compare=False)


PAGES: dict[str, Page] = {p.path: p for p in (
    Page("/", "Hazard forecasts you can verify",
         "Research forecasts for earthquakes, hurricane rapid intensification and US tornadoes, each traceable to "
         "its data, model and track record."),
    Page("/live/", "Current forecasts",
         "Every current HazardPulse forecast on one page: earthquake chances by grid cell, hurricane rapid "
         "intensification, and US tornado chances by storm."),
    Page("/live/earthquake/", "Earthquake forecast: 30-day chance of M6+",
         "The chance of a magnitude 6+ earthquake in each 2-degree grid cell worldwide over the next 30 days, "
         "with the model's test record. Not a prediction."),
    Page("/live/hurricane/", "Hurricane rapid intensification, next 24 hours",
         "For each active tropical cyclone, the chance it strengthens by 30 knots or more in 24 hours: NOAA's "
         "guidance where it exists, our model elsewhere."),
    Page("/live/tornado/", "Tornado chance by storm, next 60 minutes",
         "For every thunderstorm NOAA tracks over the contiguous US, the chance it produces a tornado within 60 "
         "minutes. A research forecast: follow NWS warnings."),
    Page("/verification/", "Track record",
         "How each HazardPulse model scored on held-back years, and how its live forecasts are scoring as their "
         "windows close, including what is not yet known."),
    Page("/verification/tornado/", "Tornado model test results",
         "How the HazardPulse tornado model scored on every tracked US storm of 2025, compared with NOAA ProbTor "
         "and NWS warnings on the same storms.", static=True),
    Page("/verification/cross-modality/", "Research: precursor tests",
         "Tests of whether geomagnetic, solar and lightning signals differ before earthquakes, rapid "
         "intensification and tornadoes, published whatever they find."),
    Page("/evidence/", "Evidence",
         "For each published forecast: its inputs, file hashes, quality-check result and a replay file you can "
         "download to check or reproduce it."),
    Page("/methods/", "Methods",
         "What data each HazardPulse forecast uses, how each model was chosen and tested, its known limits, and "
         "the checks run before publishing.", static=True),
    Page("/registry/", "Model registry",
         "Every HazardPulse model version: what it forecasts, whether it is published, experimental or retired, "
         "its test result, and why it changed.", static=True),
    Page("/api/", "API",
         "Read-only JSON API for HazardPulse forecasts, evidence records, model registry and track record. No key "
         "required. Versioned contracts.", static=True),
    Page("/ops/status/", "System status",
         "Whether each HazardPulse forecast is current, when it last published, and what its quality checks "
         "found."),
    Page("/legal/disclaimer/", "Disclaimer",
         "HazardPulse publishes research forecasts, not official warnings. How to read a probability, and where "
         "to find official hazard information.", static=True),
    Page("/legal/privacy/", "Privacy",
         "No accounts, no ads, no tracking. One cookie for your theme. What the site does and does not collect.",
         static=True),
    Page("/legal/terms/", "Terms of use",
         "Terms for using HazardPulse and its API: a research service, not a warning system, provided as is. Code "
         "under AGPL-3.0; commercial licences available.", static=True),
    Page("/404.html", "Page not found",
         "This page does not exist. Go to the current HazardPulse forecasts, or to official warnings from the NWS, "
         "NHC and USGS.", static=True, noindex=True),
)}

NAV: tuple = (
    ("Live", "/live/", (("Earthquake", "/live/earthquake/", "eq"), ("Hurricane", "/live/hurricane/", "hu"),
                        ("Tornado", "/live/tornado/", "to"))),
    ("Track record", "/verification/", ()),
    ("Evidence", "/evidence/", ()),
    ("Methods", "/methods/", ()),
    ("Models", "/registry/", ()),
    ("API", "/api/", ()),
)

FOOTER: tuple = (
    ("Forecasts", (("Live overview", "/live/"), ("Earthquake", "/live/earthquake/"),
                   ("Hurricane", "/live/hurricane/"), ("Tornado", "/live/tornado/"))),
    ("Proof", (("Track record", "/verification/"), ("Evidence", "/evidence/"), ("Methods", "/methods/"),
               ("Model registry", "/registry/"), ("Research tests", "/verification/cross-modality/"))),
    ("Developers", (("API", "/api/"), ("System status", "/ops/status/"), ("Open data", DATA_RELEASE_URL),
                    ("Source code", SOURCE_URL), ("RSS feed", "/feed.xml"))),
    ("Legal", (("Disclaimer", "/legal/disclaimer/"), ("Privacy", "/legal/privacy/"),
               ("Terms of use", "/legal/terms/"), ("Commercial licence", "/COMMERCIAL_LICENSE.md"),
               ("Contact", f"mailto:{CONTACT_EMAIL}"))),
)

ICON_SUN = ('<svg class="icon icon-sun" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="12" '
            'cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4'
            'M17.7 6.3l1.4-1.4"/></svg>')
ICON_MOON = ('<svg class="icon icon-moon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M21 '
             '12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg>')


def esc(value) -> str:
    return html.escape("" if value is None else str(value), quote=True)


@lru_cache(maxsize=None)
def _asset_version(name: str, mtime_ns: int) -> str:
    return hashlib.sha256((DIST / "assets" / name).read_bytes().replace(b"\r\n", b"\n")).hexdigest()[:10]


def asset(name: str) -> str:
    """``/assets/<name>?v=<content hash>``: /assets is cached for a year, so every change to a file must
    change its URL, or returning visitors would keep the old one."""
    p = DIST / "assets" / name
    return f"/assets/{name}?v={_asset_version(name, p.stat().st_mtime_ns)}" if p.exists() else f"/assets/{name}"


STYLESHEET = "styles.css"
_STYLESHEET_ASSET = re.compile(r'url\("/assets/([^"?#]+)(?:\?v=[0-9a-f]{10})?"\)')


def versioned_stylesheet(text: str) -> str:
    """The stylesheet's own references into /assets (its fonts) carry their content hash, exactly as the
    page's preload does. The two must be one URL: with ``?v=`` on the preload alone, every visitor fetched
    the font twice and the preload was wasted (found 2026-10-05). It also makes a changed font a new URL, and
    so a new stylesheet hash, under the year-long cache."""
    return _STYLESHEET_ASSET.sub(lambda m: f'url("{asset(m.group(1))}")', text)


def version_stylesheet() -> bool:
    """Rewrite the stylesheet's asset URLs to their current hashes; True if it changed. Run before pages are
    rendered, since every page names the stylesheet by its own hash."""
    p = DIST / "assets" / STYLESHEET
    if not p.exists():
        return False
    text = p.read_text(encoding="utf-8")
    new = versioned_stylesheet(text)
    if new == text:
        return False
    p.write_text(new, encoding="utf-8", newline="\n")
    return True


def page_for(path: str) -> Page:
    if path not in PAGES:
        raise KeyError(f"{path} is not a registered page (add it to hazardpulse.site.shell.PAGES)")
    return PAGES[path]


def full_title(page: Page) -> str:
    return "HazardPulse — " + page.title if page.path == "/" else f"{page.title} — HazardPulse"


def head(path: str, extra_head: str = "") -> str:
    page = page_for(path)
    title, desc = esc(full_title(page)), esc(page.description)
    url = DOMAIN + ("/" if path == "/404.html" else path)
    lines = [
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{title}</title>",
        f'<meta name="description" content="{desc}">',
        '<meta name="color-scheme" content="light dark">',
        '<meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">',
        '<meta name="theme-color" content="#0b1220" media="(prefers-color-scheme: dark)">',
        ('<meta name="robots" content="noindex">' if page.noindex else f'<link rel="canonical" href="{url}">'),
        f'<link rel="preload" href="{asset("fonts/inter-latin.woff2")}" as="font" type="font/woff2" crossorigin>',
        f'<link rel="stylesheet" href="{asset("styles.css")}">',
        f'<script src="{asset("site-shell.js")}"></script>',
        f'<link rel="icon" type="image/png" sizes="32x32" href="{asset("favicon-32.png")}">',
        f'<link rel="apple-touch-icon" sizes="180x180" href="{asset("apple-touch-icon.png")}">',
        '<link rel="alternate" type="application/rss+xml" title="HazardPulse" href="/feed.xml">',
        '<meta property="og:type" content="website">',
        '<meta property="og:site_name" content="HazardPulse">',
        f'<meta property="og:title" content="{title}">',
        f'<meta property="og:description" content="{desc}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:image" content="{DOMAIN}{OG_IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta property="og:image:alt" content="HazardPulse — hazard forecasts you can verify">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{title}">',
        f'<meta name="twitter:description" content="{desc}">',
        f'<meta name="twitter:image" content="{DOMAIN}{OG_IMAGE}">',
    ]
    if page.jsonld:
        lines.append('<script type="application/ld+json">' + json.dumps(page.jsonld, separators=(",", ":"))
                     + "</script>")
    if extra_head:
        lines.append(extra_head.strip())
    return "<head>\n  " + "\n  ".join(lines) + "\n</head>"


def _active(path: str, href: str) -> bool:
    return path == href or (href != "/" and path.startswith(href))


def header(path: str) -> str:
    items = []
    for label, href, children in NAV:
        cur = ' aria-current="page"' if _active(path, href) else ""
        if children:
            sub = "".join(f'<a href="{c_href}"{" aria-current=" + chr(34) + "page" + chr(34) if path == c_href else ""}>'
                          f'<span class="hazard-dot {code}" aria-hidden="true"></span>{esc(c_label)}</a>'
                          for c_label, c_href, code in children)
            items.append(f'<div class="nav-group"><a class="nav-link" href="{href}"{cur}>{esc(label)}</a>'
                         f'<div class="nav-sub">{sub}</div></div>')
        else:
            items.append(f'<a class="nav-link" href="{href}"{cur}>{esc(label)}</a>')
    nav = "".join(items)
    return f"""<a class="skip-link" href="#main">Skip to content</a>
<div class="emergency-banner" role="alert" aria-live="polite"></div>
<header class="site-header" role="banner">
  <div class="container header-inner">
    <a class="brand" href="/" aria-label="HazardPulse home"><img class="brand-logo" src="{asset("hp-mark.svg")}" alt="" width="28" height="28"><span>HazardPulse</span></a>
    <nav class="site-nav" aria-label="Primary">{nav}</nav>
    <div class="header-actions">
      <button class="theme-toggle" type="button" aria-label="Switch colour theme" aria-pressed="false">{ICON_SUN}{ICON_MOON}</button>
      <details class="mobile-nav">
        <summary aria-label="Menu"><span class="menu-bars" aria-hidden="true"></span></summary>
        <nav class="mobile-nav-panel" aria-label="Mobile">{nav}</nav>
      </details>
    </div>
  </div>
</header>"""


def footer() -> str:
    cols = "".join(
        f'<div class="footer-col"><h2 class="footer-heading">{esc(title)}</h2><ul>'
        + "".join(f'<li><a href="{esc(href)}">{esc(label)}</a></li>' for label, href in links)
        + "</ul></div>" for title, links in FOOTER)
    return f"""<footer class="site-footer" role="contentinfo">
  <div class="container">
    <div class="footer-top">
      <div class="footer-brand">
        <a class="brand" href="/"><img class="brand-logo" src="{asset("hp-mark.svg")}" alt="" width="28" height="28"><span>HazardPulse</span></a>
        <p>Hazard forecasts you can verify. Every number links to its data, its model and its track record.</p>
      </div>
      <div class="footer-cols">{cols}</div>
    </div>
    <div class="footer-bottom">
      <p class="footer-warning"><strong>Not an official warning service.</strong> In an emergency, follow your national weather and geological services and local authorities &mdash; in the United States, the <a href="https://www.weather.gov/">National Weather Service</a>, the <a href="https://www.nhc.noaa.gov/">National Hurricane Center</a> and the <a href="https://earthquake.usgs.gov/">USGS</a>.</p>
      <p class="footer-legal">&copy; {YEAR} HazardPulse &middot; Code under AGPL-3.0, <a href="/COMMERCIAL_LICENSE.md">commercial licence</a> available &middot; Data from NOAA, USGS and the public archives credited on each page</p>
    </div>
  </div>
</footer>"""


def document(path: str, main_html: str, *, extra_head: str = "", body_class: str = "", scripts: tuple = ()) -> str:
    """The whole page. ``main_html`` is the page's own content (a ``<main id="main">`` element or its
    inner HTML); ``scripts`` are /assets file names loaded deferred at the end of the body."""
    main = main_html.strip()
    if not main.startswith("<main"):
        main = f'<main id="main" class="page">\n{main}\n</main>'
    tail = "".join(f'\n<script src="{asset(s)}" defer></script>' for s in scripts)
    cls = f' class="{esc(body_class)}"' if body_class else ""
    return (f'<!doctype html>\n<html lang="en">\n{head(path, extra_head)}\n<body{cls}>\n{header(path)}\n{main}\n'
            f"{footer()}{tail}\n</body>\n</html>\n")


MAIN_RE = re.compile(r"<main\b[^>]*>.*</main>", re.S)


def extract_main(page_html: str) -> str:
    m = MAIN_RE.search(page_html)
    if not m:
        raise ValueError("page has no <main> element")
    return m.group(0)


def static_page_file(path: str, dist: Path | None = None) -> Path:
    """The file a site path is served from: ``/`` -> index.html, ``/a/b/`` -> a/b/index.html."""
    base = dist or DIST
    if path == "/404.html":
        return base / "404.html"
    inner = path.strip("/")
    return base / inner / "index.html" if inner else base / "index.html"


EXTRA_HEAD_RE = re.compile(r"<!-- page-head -->.*?<!-- /page-head -->", re.S)
SCRIPTS_RE = re.compile(r'<script src="/assets/([^"?]+)(?:\?v=[0-9a-f]+)?" defer></script>')


def rewrapped(path: str, dist: Path | None = None) -> str:
    """A hand-kept page in the current shell: its own <main>, its page-specific head block (between
    ``<!-- page-head -->`` markers) and its deferred scripts, inside today's head, header and footer."""
    old = static_page_file(path, dist).read_text(encoding="utf-8")
    body_class = (re.search(r'<body class="([^"]*)"', old) or [None, ""])[1]
    extra = EXTRA_HEAD_RE.search(old)
    tail = old[old.rfind("</footer>"):] if "</footer>" in old else ""
    head_extra = (extra.group(0) if extra else "") + jsonld_for(path, None)
    return document(path, extract_main(old), extra_head=head_extra, body_class=body_class,
                    scripts=tuple(SCRIPTS_RE.findall(tail)))


def rewrap(path: str, dist: Path | None = None) -> bool:
    """Re-wrap one hand-kept page; True when it changed."""
    f = static_page_file(path, dist)
    old = f.read_text(encoding="utf-8")
    new = rewrapped(path, dist)
    if new != old:
        f.write_text(new, encoding="utf-8", newline="\n")
        return True
    return False


def rewrap_static_pages(dist: Path | None = None) -> list[str]:
    return [p.path for p in PAGES.values()
            if p.static and static_page_file(p.path, dist).exists() and rewrap(p.path, dist)]


ORG = {"@type": "Organization", "name": "HazardPulse", "url": DOMAIN + "/",
       "logo": DOMAIN + "/assets/apple-touch-icon.png", "email": CONTACT_EMAIL}


def jsonld_for(path: str, d=None) -> str:
    """Structured data for the pages that carry it: the site itself, and the forecast datasets."""
    graph: list[dict] = []
    if path == "/":
        graph = [{"@type": "WebSite", "name": "HazardPulse", "url": DOMAIN + "/",
                  "description": PAGES["/"].description, "publisher": ORG}, ORG]
    elif path in ("/live/", "/live/earthquake/", "/live/hurricane/", "/live/tornado/", "/evidence/"):
        files = {"/live/": "/data/live-pulse.json", "/live/earthquake/": "/api/v1/live/earthquake",
                 "/live/hurricane/": "/data/live-storms.json", "/live/tornado/": "/data/live-tornadoes.json",
                 "/evidence/": "/data/evidence/replay-index.json"}
        page = PAGES[path]
        ds = {"@type": "Dataset", "name": page.title, "description": page.description, "url": DOMAIN + path,
              "creator": ORG, "isAccessibleForFree": True,
              "license": DOMAIN + "/legal/terms/",
              "distribution": [{"@type": "DataDownload", "encodingFormat": "application/json",
                                "contentUrl": DOMAIN + files[path]}]}
        if d is not None and getattr(d, "built_at", None):
            ds["dateModified"] = d.built_at
        graph = [ds]
    if not graph:
        return ""
    doc = {"@context": "https://schema.org", "@graph": graph}
    return '<script type="application/ld+json">' + json.dumps(doc, separators=(",", ":")) + "</script>"
